### ISSUE TITLE
exec /usr/local/bin/prep.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by tomglvng** [lugosidomotor/DockerLocalWordPress#2]
On Linux, when launching

`docker-compose up -d && docker-compose exec wordpress prep.sh
`
I've got
`
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/local/bin/prep.sh: no such file or directory: unknown`

Any idea?

**Comment by lugosidomotor** [comment]
The path/permission will be the problem with the "docker-compose exec wordpress prep.sh".
Please try this:
1. docker-compose up -d
2. Exec inside the wordpress container: docker exec -ti dockerlocalpress_wordpress_1 bash
3. Start manually the prep.sh: cd /usr/local/bin/ && bash prep.sh

**Comment by tomglvng** [comment]
I saw you updated, and now it's working. Thanks!

**Comment by tomglvng** [comment]
Fixed
